// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aczyexlsaulsikieyzee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjenlleGxzYXVsc2lraWV5emVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjY3NTUsImV4cCI6MjA2OTcwMjc1NX0.eN3W8fCaagee4Q2l_aVK3CGATmM8E92D0zRMnNfhf0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
